name 'evenup-hubot'
version '0.1.2'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages hubot'
description 'Installs, configures, and runs a hubot bot by configuring all parameters or as config from a git repo'
project_page 'https://github.com/evenup/evenup-hubot'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/nodejs', '>= 0.2.0'
#dependency 'puppetlabs/vcsrep', '>=0 .1.2'
#dependency 'puppetlabs/git', '>= 0.0.3'
